version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    container_name: es01
    environment:
      discovery.type: single-node
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:6.8.13
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic


networks:
  elastic:
    driver: bridge
